version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-manager-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:taskdb
      - SPRING_H2_CONSOLE_ENABLED=true
      - SERVER_PORT=8080
      - SPRING_WEB_CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8081,http://frontend:8081
    volumes:
      - backend_data:/app/data
    networks:
      - taskmanager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.2'

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-manager-frontend
    ports:
      - "8081:8081"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - taskmanager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
        reservations:
          memory: 64M
          cpus: '0.1'

  # Reverse Proxy (Optional - for production-like setup)
  nginx-proxy:
    image: nginx:alpine
    container_name: task-manager-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - taskmanager-network
    restart: unless-stopped
    profiles:
      - production

volumes:
  backend_data:
    driver: local

networks:
  taskmanager-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16